Repository EricLBuehler/mistral.rs, pull requests merged in 2024-04, with the labels that each got.

#65 Move sampler into mistralrs
  examples/http.md
  mistralrs-core/Cargo.toml
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/lib.rs
  mistralrs-core/src/pipeline/gemma.rs
  mistralrs-core/src/pipeline/llama.rs
  mistralrs-core/src/pipeline/mistral.rs
  mistralrs-core/src/pipeline/mixtral.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/request.rs
  mistralrs-core/src/response.rs
  mistralrs-core/src/sampler.rs
  mistralrs-core/src/sampling.rs
  mistralrs-core/src/sequence.rs
  mistralrs-server/src/main.rs
Labels: processing

#68 Fix Decoding during Streaming
  .cargo/config.toml
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/sequence.rs
Labels: processing

#69 Avoid calculating logprobs if unneded
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/pipeline/gemma.rs
  mistralrs-core/src/pipeline/llama.rs
  mistralrs-core/src/pipeline/mistral.rs
  mistralrs-core/src/pipeline/mixtral.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/sampler.rs
Labels: optimization, processing

#70 Optimize argmax by using tensor op
  mistralrs-core/src/sampler.rs
Labels: optimization, processing

#76 Add guide for adding models
  ADDING_MODELS.md
  README.md
  mistralrs-core/src/models/gemma.rs
  mistralrs-core/src/models/llama.rs
  mistralrs-core/src/models/mistral.rs
  mistralrs-core/src/models/mixtral.rs
  mistralrs-core/src/models/mod.rs
  mistralrs-core/src/models/quantized_llama.rs
  mistralrs-core/src/xlora_models/gemma.rs
  mistralrs-core/src/xlora_models/llama.rs
  mistralrs-core/src/xlora_models/mistral.rs
  mistralrs-core/src/xlora_models/mixtral.rs
  mistralrs-core/src/xlora_models/quantized_llama.rs
Labels: documentation, models

#85 Implement Phi2 model
  README.md
  examples/server/chat.py
  examples/server/streaming.py
  mistralrs-core/src/lib.rs
  mistralrs-core/src/models/mod.rs
  mistralrs-core/src/models/phi2.rs
  mistralrs-core/src/models/quantized_llama.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/pipeline/phi2.rs
  mistralrs-core/src/xlora_models/mod.rs
  mistralrs-core/src/xlora_models/phi2.rs
  mistralrs-core/src/xlora_models/quantized_llama.rs
  mistralrs-server/src/main.rs
  mistralrs-server/src/model_selected.rs
  mistralrs/src/lib.rs
Labels: new feature, models

#89 Get gguf context length from metadata
  mistralrs-core/src/models/quantized_llama.rs
  mistralrs-core/src/pipeline/llama.rs
  mistralrs-core/src/pipeline/mistral.rs
  mistralrs-core/src/pipeline/mixtral.rs
  mistralrs-core/src/xlora_models/quantized_llama.rs
Labels: fix

#90 Remove Rc<RefCell<Sequence>>
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/pipeline/gemma.rs
  mistralrs-core/src/pipeline/llama.rs
  mistralrs-core/src/pipeline/mistral.rs
  mistralrs-core/src/pipeline/mixtral.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/pipeline/phi2.rs
  mistralrs-core/src/scheduler.rs
  mistralrs-core/src/sequence.rs
  mistralrs-core/src/utils/mod.rs
Labels: optimization, backend

#93 Implement merging for Lora layers
  mistralrs-lora/src/lib.rs
  mistralrs-lora/src/loralinear.rs
  mistralrs-lora/src/qloralinear.rs
Labels: new feature, models

#94 Allow input prompt message to be a String prompt
  examples/http.md
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/request.rs
  mistralrs-pyo3/Cargo.toml
  mistralrs-pyo3/mistralrs.pyi
  mistralrs-pyo3/src/lib.rs
  mistralrs-server/Cargo.toml
  mistralrs-server/src/main.rs
  mistralrs-server/src/openai.rs
Labels: new feature

#96 Remove sync calls and reorder cache ops
  mistralrs-core/src/engine/mod.rs
Labels: optimization

#100 Add support for LoRA
  README.md
  mistralrs-core/src/models/mod.rs
  mistralrs-core/src/models/quantized_llama.rs
  mistralrs-core/src/pipeline/gemma.rs
  mistralrs-core/src/pipeline/llama.rs
  mistralrs-core/src/pipeline/mistral.rs
  mistralrs-core/src/pipeline/mixtral.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/pipeline/phi2.rs
  mistralrs-core/src/xlora_models/gemma.rs
  mistralrs-core/src/xlora_models/llama.rs
  mistralrs-core/src/xlora_models/mistral.rs
  mistralrs-core/src/xlora_models/mixtral.rs
  mistralrs-core/src/xlora_models/mod.rs
  mistralrs-core/src/xlora_models/phi2.rs
  mistralrs-core/src/xlora_models/quantized_llama.rs
  mistralrs-lora/src/frozenlinear.rs
  mistralrs-lora/src/lib.rs
  mistralrs-lora/src/loralinear.rs
  mistralrs-lora/src/qloralinear.rs
  mistralrs-server/src/main.rs
  mistralrs-server/src/model_selected.rs
  orderings/default-ordering.json
Labels: new feature, models

#102 Implement an interactive mode
  README.md
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/sampler.rs
  mistralrs-pyo3/src/lib.rs
  mistralrs-server/src/interactive_mode.rs
  mistralrs-server/src/main.rs
Labels: new feature

#103 Constrained decoding
  examples/server/c.y
  examples/server/regex.py
  examples/server/yacc.py
  mistralrs-core/Cargo.toml
  mistralrs-core/src/aici/README.md
  mistralrs-core/src/aici/bintokens.rs
  mistralrs-core/src/aici/bytes.rs
  mistralrs-core/src/aici/cfg.rs
  mistralrs-core/src/aici/lex.rs
  mistralrs-core/src/aici/mod.rs
  mistralrs-core/src/aici/recognizer.rs
  mistralrs-core/src/aici/rx.rs
  mistralrs-core/src/aici/svob.rs
  mistralrs-core/src/aici/toktree.rs
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/lib.rs
  mistralrs-core/src/pipeline/gemma.rs
  mistralrs-core/src/pipeline/llama.rs
  mistralrs-core/src/pipeline/mistral.rs
  mistralrs-core/src/pipeline/mixtral.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/pipeline/phi2.rs
  mistralrs-core/src/request.rs
  mistralrs-core/src/sequence.rs
  mistralrs-core/src/utils/mod.rs
  mistralrs-pyo3/src/lib.rs
  mistralrs-server/src/interactive_mode.rs
  mistralrs-server/src/main.rs
  mistralrs-server/src/openai.rs
  mistralrs/src/lib.rs
Labels: new feature, models, processing

#95 Implement prefix caching
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/lib.rs
  mistralrs-core/src/prefix_cacher.rs
  mistralrs-core/src/scheduler.rs
  mistralrs-core/src/sequence.rs
Labels: new feature, optimization, backend, processing

#108 Optimize qllama MQA impl
  mistralrs-core/src/models/quantized_llama.rs
  mistralrs-core/src/xlora_models/quantized_llama.rs
Labels: optimization

#107 Add the /v1/completion endpoint
  examples/http.md
  examples/server/completion.py
  examples/server/streaming.py
  integrations/llama_index_integration.py
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/lib.rs
  mistralrs-core/src/request.rs
  mistralrs-core/src/response.rs
  mistralrs-core/src/sequence.rs
  mistralrs-core/src/utils/mod.rs
  mistralrs-pyo3/API.md
  mistralrs-pyo3/README.md
  mistralrs-pyo3/mistralrs.pyi
  mistralrs-pyo3/src/lib.rs
  mistralrs-server/src/chat_completion.rs
  mistralrs-server/src/completions.rs
  mistralrs-server/src/interactive_mode.rs
  mistralrs-server/src/main.rs
  mistralrs-server/src/openai.rs
  mistralrs/src/lib.rs
Labels: new feature, models, processing

#115 Handle error in regex compilation
  mistralrs-core/src/aici/rx.rs
  mistralrs-core/src/engine/mod.rs
Labels: fix

#119 Implement a single prompt mode
  README.md
  mistralrs-server/src/main.rs
  mistralrs-server/src/prompt_mode.rs
Labels: new feature

#116 Support multiple stop tokens
  mistralrs-core/Cargo.toml
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/pipeline/gemma.rs
  mistralrs-core/src/pipeline/llama.rs
  mistralrs-core/src/pipeline/mistral.rs
  mistralrs-core/src/pipeline/mixtral.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/pipeline/phi2.rs
  mistralrs-core/src/sampler.rs
  mistralrs-core/src/sequence.rs
  mistralrs-server/src/chat_completion.rs
  mistralrs-server/src/completions.rs
  mistralrs-server/src/openai.rs
Labels: new feature, optimization

#120 Fix completions endpoint example
  examples/http.md
Labels: fix

#124 Fix prefix caching
  mistralrs-core/src/prefix_cacher.rs
Labels: fix

#122 Remove stop from response
  examples/server/chat.py
  examples/server/completion.py
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/sequence.rs
Labels: processing

#128 Optimize streaming
  examples/server/stream_completion_bench.py
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/sequence.rs
Labels: optimization

#133 Implement prefix caching for xlora cache
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/prefix_cacher.rs
  mistralrs-core/src/sequence.rs
  mistralrs-core/src/xlora_models/config.rs
  mistralrs-core/src/xlora_models/mod.rs
Labels: new feature

#140 Rework the prefix cacher
  Cargo.toml
  mistralrs-core/Cargo.toml
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/prefix_cacher.rs
  mistralrs-core/src/sequence.rs
  mistralrs-core/src/utils/mod.rs
Labels: optimization

#162 Optimize quantized masked fill
  mistralrs-core/src/models/quantized_llama.rs
Labels: optimization

#166 mistralrs-bench
  Cargo.toml
  mistralrs-bench/Cargo.toml
  mistralrs-bench/src/main.rs
  mistralrs-core/Cargo.toml
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/lib.rs
  mistralrs-core/src/model_loader.rs
  mistralrs-core/src/model_selected.rs
  mistralrs-core/src/prefix_cacher.rs
  mistralrs-core/src/request.rs
  mistralrs-core/src/sequence.rs
  mistralrs-pyo3/src/lib.rs
  mistralrs-pyo3/src/loaders/gemma.rs
  mistralrs-pyo3/src/loaders/llama.rs
  mistralrs-pyo3/src/loaders/mistral.rs
  mistralrs-pyo3/src/loaders/mixtral.rs
  mistralrs-pyo3/src/loaders/phi2.rs
  mistralrs-server/Cargo.toml
  mistralrs-server/src/chat_completion.rs
  mistralrs-server/src/completions.rs
  mistralrs-server/src/interactive_mode.rs
  mistralrs-server/src/main.rs
  mistralrs-server/src/prompt_mode.rs
  mistralrs/src/lib.rs
Labels: new feature

#171 Add streaming support to PyO3
  Cargo.toml
  examples/python/streaming.py
  integrations/llama_index_integration.py
  mistralrs-pyo3/API.md
  mistralrs-pyo3/Cargo.toml
  mistralrs-pyo3/mistralrs.pyi
  mistralrs-pyo3/src/lib.rs
  mistralrs-pyo3/src/stream.rs
  mistralrs-server/Cargo.toml
Labels: new feature, pyo3

#178 Add Llama3 Support
  README.md
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/models/llama.rs
  mistralrs-core/src/pipeline/gemma.rs
  mistralrs-core/src/pipeline/llama.rs
  mistralrs-core/src/pipeline/mistral.rs
  mistralrs-core/src/pipeline/mixtral.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/pipeline/phi2.rs
  mistralrs-core/src/prefix_cacher.rs
  mistralrs-core/src/sequence.rs
  mistralrs-core/src/xlora_models/llama.rs
Labels: models

#187 Fix the gemma models
  mistralrs-core/src/models/gemma.rs
  mistralrs-core/src/pipeline/gemma.rs
  mistralrs-core/src/xlora_models/gemma.rs
Labels: fix

#175 Better PyO3 API ergonomics
  .github/workflows/docs.yml
  Cargo.toml
  README.md
  docs/ADAPTER_MODELS.md
  docs/ADDING_MODELS.md
  docs/CHAT_TOK.md
  docs/CMD_LINE_DOCS.md
  docs/INSTALLATION.md
  examples/python/bare_bones.py
  examples/python/cookbook.ipynb
  examples/python/python_api.py
  examples/python/streaming.py
  examples/python/xlora_gemma.py
  examples/python/xlora_zephyr.py
  integrations/llama_index_integration.py
  mistralrs-core/Cargo.toml
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/lib.rs
  mistralrs-core/src/pipeline/gemma.rs
  mistralrs-core/src/pipeline/llama.rs
  mistralrs-core/src/pipeline/mistral.rs
  mistralrs-core/src/pipeline/mixtral.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/pipeline/phi2.rs
  mistralrs-core/src/response.rs
  mistralrs-core/src/sampler.rs
  mistralrs-core/src/utils/mod.rs
  mistralrs-core/src/xlora_models/config.rs
  mistralrs-lora/src/lib.rs
  mistralrs-pyo3/API.md
  mistralrs-pyo3/Cargo.toml
  mistralrs-pyo3/README.md
  mistralrs-pyo3/mistralrs.pyi
  mistralrs-pyo3/src/lib.rs
  mistralrs-pyo3/src/loaders/gemma.rs
  mistralrs-pyo3/src/loaders/llama.rs
  mistralrs-pyo3/src/loaders/mistral.rs
  mistralrs-pyo3/src/loaders/mixtral.rs
  mistralrs-pyo3/src/loaders/mod.rs
  mistralrs-pyo3/src/loaders/phi2.rs
  mistralrs-pyo3/src/message.rs
  mistralrs-pyo3/src/stream.rs
  mistralrs-pyo3/src/which.rs
  mistralrs-server/src/chat_completion.rs
  mistralrs-server/src/interactive_mode.rs
  orderings/xlora-gemma-paper-ordering.json
  orderings/xlora-paper-ordering.json
  scripts/create_ordering.py
Labels: documentation, new feature, pyo3

#188 Add Rust API examples
  README.md
  mistralrs-core/src/sampler.rs
  mistralrs/Cargo.toml
  mistralrs/README.md
  mistralrs/examples/grammar/main.rs
  mistralrs/examples/simple/main.rs
  mistralrs/src/lib.rs
Labels: documentation

#189 Add the quantized phi2 model
  README.md
  mistralrs-core/src/model_loader.rs
  mistralrs-core/src/model_selected.rs
  mistralrs-core/src/models/gemma.rs
  mistralrs-core/src/models/llama.rs
  mistralrs-core/src/models/mistral.rs
  mistralrs-core/src/models/mixtral.rs
  mistralrs-core/src/models/mod.rs
  mistralrs-core/src/models/phi2.rs
  mistralrs-core/src/models/quantized_llama.rs
  mistralrs-core/src/models/quantized_phi2.rs
  mistralrs-core/src/pipeline/phi2.rs
  mistralrs-core/src/xlora_models/gemma.rs
  mistralrs-core/src/xlora_models/llama.rs
  mistralrs-core/src/xlora_models/mistral.rs
  mistralrs-core/src/xlora_models/mixtral.rs
  mistralrs-core/src/xlora_models/phi2.rs
  mistralrs-core/src/xlora_models/quantized_llama.rs
  mistralrs-pyo3/mistralrs.pyi
  mistralrs-pyo3/src/lib.rs
  mistralrs-pyo3/src/which.rs
Labels: models

#193 Fix non granular state
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/pipeline/mod.rs
Labels: fix

#194 Fix the sequence len calculation for xlora
  mistralrs-core/src/sequence.rs
Labels: fix

#197 Improve the Llama Index integration
  examples/llama_index/mistral_gguf.py
  examples/llama_index/xlora_gguf.py
  integrations/llama_index_integration.py
Labels: fix, pyo3

#201 Better support for jupyter by silent loading
  README.md
  mistralrs-bench/src/main.rs
  mistralrs-core/src/pipeline/ggml.rs
  mistralrs-core/src/pipeline/gguf.rs
  mistralrs-core/src/pipeline/macros.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/pipeline/normal.rs
  mistralrs-pyo3/src/lib.rs
  mistralrs-server/src/main.rs
  mistralrs/examples/grammar/main.rs
  mistralrs/examples/quantized/main.rs
  mistralrs/examples/simple/main.rs
Labels: fix, pyo3

#157 Implement device offloading
  README.md
  mistralrs-bench/src/main.rs
  mistralrs-core/src/device_map.rs
  mistralrs-core/src/lib.rs
  mistralrs-core/src/models/gemma.rs
  mistralrs-core/src/models/llama.rs
  mistralrs-core/src/models/mistral.rs
  mistralrs-core/src/models/mixtral.rs
  mistralrs-core/src/models/phi2.rs
  mistralrs-core/src/models/quantized_llama.rs
  mistralrs-core/src/models/quantized_phi2.rs
  mistralrs-core/src/pipeline/ggml.rs
  mistralrs-core/src/pipeline/gguf.rs
  mistralrs-core/src/pipeline/loaders.rs
  mistralrs-core/src/pipeline/macros.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/pipeline/normal.rs
  mistralrs-core/src/xlora_models/gemma.rs
  mistralrs-core/src/xlora_models/llama.rs
  mistralrs-core/src/xlora_models/mistral.rs
  mistralrs-core/src/xlora_models/mixtral.rs
  mistralrs-core/src/xlora_models/phi2.rs
  mistralrs-core/src/xlora_models/quantized_llama.rs
  mistralrs-pyo3/mistralrs.pyi
  mistralrs-pyo3/src/lib.rs
  mistralrs-server/src/main.rs
  mistralrs-server/src/prompt_mode.rs
  mistralrs/examples/grammar/main.rs
  mistralrs/examples/quantized/main.rs
  mistralrs/examples/simple/main.rs
  mistralrs/src/lib.rs
Labels: new feature, backend, models

#204 Add Phi3 Scaled RoPE, for 128K
  README.md
  mistralrs-core/src/models/layers.rs
  mistralrs-core/src/models/mod.rs
  mistralrs-core/src/models/phi3.rs
  mistralrs-core/src/models/quantized_phi2.rs
  mistralrs-core/src/pipeline/loaders.rs
  mistralrs-core/src/xlora_models/phi3.rs
Labels: new feature, models

#205 Add docs for mistralrs-bench
  mistralrs-bench/README.md
  mistralrs-bench/src/main.rs
Labels: documentation

#206 Add the Qwen2 models
  README.md
  mistralrs-core/src/lib.rs
  mistralrs-core/src/models/mod.rs
  mistralrs-core/src/models/qwen2.rs
  mistralrs-core/src/pipeline/chat_template.rs
  mistralrs-core/src/pipeline/loaders.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/pipeline/normal.rs
Labels: models

#212 Fixed erroneous space in GGUF URL
  integrations/llama_index_integration.py
Labels: fix

#209 Skip cloning cache in redundantly
  mistralrs-core/src/engine/mod.rs
Labels: optimization, backend

#218 Support local loading
  README.md
  mistralrs-core/src/model_selected.rs
  mistralrs-core/src/models/gemma.rs
  mistralrs-core/src/models/llama.rs
  mistralrs-core/src/models/mistral.rs
  mistralrs-core/src/models/mixtral.rs
  mistralrs-core/src/models/phi2.rs
  mistralrs-core/src/models/phi3.rs
  mistralrs-core/src/models/qwen2.rs
  mistralrs-core/src/pipeline/macros.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/xlora_models/gemma.rs
  mistralrs-core/src/xlora_models/llama.rs
  mistralrs-core/src/xlora_models/mistral.rs
  mistralrs-core/src/xlora_models/mixtral.rs
  mistralrs-core/src/xlora_models/phi2.rs
  mistralrs-core/src/xlora_models/phi3.rs
  mistralrs-pyo3/API.md
Labels: new feature, fix

#221 Improve documentation
  README.md
  docs/CHAT_TOK.md
  docs/CMD_LINE_DOCS.md
  docs/NON_GRANULAR.md
  examples/python/cookbook.ipynb
  mistralrs-core/src/model_selected.rs
  mistralrs-pyo3/API.md
Labels: documentation, fix

#225 Fix api_dir_list! and show better error
  mistralrs-core/src/pipeline/macros.rs
Labels: fix

#233 Async channels
  mistralrs-bench/Cargo.toml
  mistralrs-bench/src/main.rs
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/lib.rs
  mistralrs-core/src/request.rs
  mistralrs-core/src/sequence.rs
  mistralrs-core/src/utils/mod.rs
  mistralrs-pyo3/Cargo.toml
  mistralrs-pyo3/src/lib.rs
  mistralrs-pyo3/src/stream.rs
  mistralrs-server/src/chat_completion.rs
  mistralrs-server/src/completions.rs
  mistralrs-server/src/interactive_mode.rs
  mistralrs/Cargo.toml
  mistralrs/examples/grammar/main.rs
  mistralrs/examples/isq/main.rs
  mistralrs/examples/quantized/main.rs
  mistralrs/examples/simple/main.rs
Labels: new feature

#244 Sliding window for phi3
  mistralrs-core/src/layers.rs
  mistralrs-core/src/models/mistral.rs
  mistralrs-core/src/models/mixtral.rs
  mistralrs-core/src/models/phi3.rs
  mistralrs-core/src/pipeline/loaders.rs
  mistralrs-core/src/xlora_models/mistral.rs
  mistralrs-core/src/xlora_models/mixtral.rs
  mistralrs-core/src/xlora_models/phi3.rs
Labels: fix

#236 Async channels
  mistralrs-bench/Cargo.toml
  mistralrs-bench/src/main.rs
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/lib.rs
  mistralrs-core/src/request.rs
  mistralrs-core/src/sequence.rs
  mistralrs-core/src/utils/mod.rs
  mistralrs-pyo3/Cargo.toml
  mistralrs-pyo3/src/lib.rs
  mistralrs-pyo3/src/stream.rs
  mistralrs-server/src/chat_completion.rs
  mistralrs-server/src/completions.rs
  mistralrs-server/src/interactive_mode.rs
  mistralrs-server/src/main.rs
  mistralrs/Cargo.toml
  mistralrs/examples/grammar/main.rs
  mistralrs/examples/isq/main.rs
  mistralrs/examples/quantized/main.rs
  mistralrs/examples/simple/main.rs
Labels: new feature

#257 Update PyO3 to take dict
  README.md
  examples/llama_index/cookbook.ipynb
  examples/python/cookbook.ipynb
  examples/python/python_api.py
  examples/python/streaming.py
  examples/python/token_source.py
  examples/python/xlora_gemma.py
  examples/python/xlora_zephyr.py
  integrations/llama_index_integration.py
  mistralrs-pyo3/API.md
  mistralrs-pyo3/mistralrs.pyi
  mistralrs-pyo3/src/lib.rs
  mistralrs-pyo3/src/message.rs
Labels: pyo3, breaking
