Repository EricLBuehler/mistral.rs, pull requests merged in 2024-06, with the labels that each got.

#370 Fix chat template and F16/BF16 CUDA GEMM when RUST_BACKTRACE
  Cargo.toml
  mistralrs-bench/Cargo.toml
  mistralrs-core/src/lib.rs
  mistralrs-core/src/pipeline/paths.rs
  mistralrs-pyo3/Cargo.toml
  mistralrs-pyo3/Cargo_template.toml
  mistralrs-pyo3/pyproject.toml
  mistralrs-pyo3/pyproject_template.toml
  mistralrs-server/Cargo.toml
  mistralrs/Cargo.toml
Labels: urgent, fix

#383 Patch incorrect unwrap and bump version
  Cargo.toml
  mistralrs-bench/Cargo.toml
  mistralrs-pyo3/Cargo.toml
  mistralrs-pyo3/Cargo_template.toml
  mistralrs-pyo3/pyproject.toml
  mistralrs-pyo3/pyproject_template.toml
  mistralrs-pyo3/src/lib.rs
  mistralrs-server/Cargo.toml
  mistralrs/Cargo.toml
Labels: urgent, fix

#400 Add fused bias linear layer with cublaslt
  mistralrs-core/src/layers.rs
Labels: optimization

#355 Support GGUF Mixtral format where experts are in one tensor
  mistralrs-core/src/models/quantized_llama.rs
Labels: models

#415 Fix: use new slice_assign
  README.md
  docs/PHI3V.md
  examples/python/phi3v.py
  examples/server/phi3v.py
  mistralrs-core/src/vision_models/phi3.rs
Labels: fix

#414 Fix Phi-3 GGUF
  mistralrs-core/src/models/quantized_phi3.rs
  mistralrs-core/src/xlora_models/quantized_phi3.rs
Labels: fix

#417 Expose API to specify dtype during loading
  README.md
  mistralrs-bench/src/main.rs
  mistralrs-core/src/lib.rs
  mistralrs-core/src/model_loader.rs
  mistralrs-core/src/model_selected.rs
  mistralrs-core/src/pipeline/ggml.rs
  mistralrs-core/src/pipeline/gguf.rs
  mistralrs-core/src/pipeline/macros.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/pipeline/normal.rs
  mistralrs-core/src/pipeline/speculative.rs
  mistralrs-core/src/pipeline/vision.rs
  mistralrs-core/src/toml_selector.rs
  mistralrs-core/src/utils/mod.rs
  mistralrs-core/src/utils/normal.rs
  mistralrs-pyo3/src/lib.rs
  mistralrs-pyo3/src/which.rs
  mistralrs-server/src/main.rs
  mistralrs/examples/gguf_locally/main.rs
  mistralrs/examples/grammar/main.rs
  mistralrs/examples/isq/main.rs
  mistralrs/examples/lora/main.rs
  mistralrs/examples/lora_activation/main.rs
  mistralrs/examples/phi3v/main.rs
  mistralrs/examples/quantized/main.rs
  mistralrs/examples/simple/main.rs
  mistralrs/examples/xlora/main.rs
Labels: new feature

#422 Add nonzero and bitwise operators
  mistralrs-core/Cargo.toml
  mistralrs-core/build.rs
  mistralrs-core/src/cublaslt/api.rs
  mistralrs-core/src/cuda/ffi.rs
  mistralrs-core/src/cuda/mod.rs
  mistralrs-core/src/cuda/nonzero_bitwise.cu
  mistralrs-core/src/layers.rs
  mistralrs-core/src/lib.rs
  mistralrs-core/src/ops.rs
  mistralrs-core/src/vision_models/phi3.rs
Labels: new feature, optimization, backend

#426 Fix Python deps, base64 impl, add examples
  Cargo.toml
  README.md
  docs/PHI3V.md
  examples/python/cookbook.ipynb
  examples/python/phi3v_base64.py
  examples/python/phi3v_local_img.py
  examples/server/phi3v_base64.py
  examples/server/phi3v_local_img.py
  mistralrs-bench/Cargo.toml
  mistralrs-pyo3/Cargo.toml
  mistralrs-pyo3/Cargo_template.toml
  mistralrs-pyo3/README.md
  mistralrs-pyo3/pyproject.toml
  mistralrs-pyo3/pyproject_template.toml
  mistralrs-pyo3/src/lib.rs
  mistralrs-server/Cargo.toml
  mistralrs-server/src/chat_completion.rs
  mistralrs-server/src/main.rs
  mistralrs/Cargo.toml
Labels: fix

#462 Add support for cross-gpu device mapping
  README.md
  docs/DEVICE_MAPPING.md
  mistralrs-bench/src/main.rs
  mistralrs-core/src/device_map.rs
  mistralrs-core/src/lib.rs
  mistralrs-core/src/models/gemma.rs
  mistralrs-core/src/models/llama.rs
  mistralrs-core/src/models/mistral.rs
  mistralrs-core/src/models/mixtral.rs
  mistralrs-core/src/models/phi2.rs
  mistralrs-core/src/models/phi3.rs
  mistralrs-core/src/models/quantized_llama.rs
  mistralrs-core/src/models/quantized_phi2.rs
  mistralrs-core/src/models/quantized_phi3.rs
  mistralrs-core/src/models/qwen2.rs
  mistralrs-core/src/pipeline/ggml.rs
  mistralrs-core/src/pipeline/gguf.rs
  mistralrs-core/src/pipeline/normal.rs
  mistralrs-core/src/pipeline/vision.rs
  mistralrs-core/src/utils/debug.rs
  mistralrs-core/src/utils/normal.rs
  mistralrs-core/src/vision_models/phi3.rs
  mistralrs-core/src/xlora_models/gemma.rs
  mistralrs-core/src/xlora_models/llama.rs
  mistralrs-core/src/xlora_models/mistral.rs
  mistralrs-core/src/xlora_models/mixtral.rs
  mistralrs-core/src/xlora_models/phi2.rs
  mistralrs-core/src/xlora_models/phi3.rs
  mistralrs-core/src/xlora_models/quantized_llama.rs
  mistralrs-core/src/xlora_models/quantized_phi3.rs
  mistralrs-pyo3/mistralrs.pyi
  mistralrs-pyo3/src/lib.rs
  mistralrs-server/src/main.rs
Labels: new feature, backend

#487 Optimize decoding by removing redundant qkv transpose
  mistralrs-core/src/models/gemma.rs
  mistralrs-core/src/models/llama.rs
  mistralrs-core/src/models/mistral.rs
  mistralrs-core/src/models/mixtral.rs
  mistralrs-core/src/models/phi2.rs
  mistralrs-core/src/models/phi3.rs
  mistralrs-core/src/models/quantized_llama.rs
  mistralrs-core/src/models/quantized_phi3.rs
  mistralrs-core/src/models/qwen2.rs
  mistralrs-core/src/vision_models/phi3.rs
  mistralrs-core/src/xlora_models/gemma.rs
  mistralrs-core/src/xlora_models/llama.rs
  mistralrs-core/src/xlora_models/mistral.rs
  mistralrs-core/src/xlora_models/mixtral.rs
  mistralrs-core/src/xlora_models/phi3.rs
  mistralrs-core/src/xlora_models/quantized_llama.rs
  mistralrs-core/src/xlora_models/quantized_phi3.rs
Labels: optimization

#490 Add the Gemma 2 model
  README.md
  docs/GEMMA2.md
  examples/python/gguf.py
  mistralrs-core/src/aici/bintokens.rs
  mistralrs-core/src/models/gemma2.rs
  mistralrs-core/src/models/mod.rs
  mistralrs-core/src/pipeline/chat_template.rs
  mistralrs-core/src/pipeline/normal.rs
  mistralrs-core/src/pipeline/normal_loaders.rs
  mistralrs-core/src/pipeline/sampling_pipeline.rs
  mistralrs-pyo3/mistralrs.pyi
  mistralrs-pyo3/src/which.rs
  mistralrs/examples/gemma2/main.rs
Labels: new feature, models

#468 Add a vision interactive mode
  README.md
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-server/src/interactive_mode.rs
  mistralrs-server/src/main.rs
Labels: new feature
