Repository EricLBuehler/mistral.rs, pull requests merged in 2024-05, with the labels that each got.

#261 Major pipeline refactor
  mistralrs-bench/src/main.rs
  mistralrs-core/Cargo.toml
  mistralrs-core/src/aici/cfg.rs
  mistralrs-core/src/device_map.rs
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/lib.rs
  mistralrs-core/src/models/gemma.rs
  mistralrs-core/src/models/llama.rs
  mistralrs-core/src/models/mistral.rs
  mistralrs-core/src/models/mixtral.rs
  mistralrs-core/src/models/phi2.rs
  mistralrs-core/src/models/phi3.rs
  mistralrs-core/src/models/quantized_llama.rs
  mistralrs-core/src/models/quantized_phi2.rs
  mistralrs-core/src/models/qwen2.rs
  mistralrs-core/src/pipeline/cache_manager.rs
  mistralrs-core/src/pipeline/chat_template.rs
  mistralrs-core/src/pipeline/ggml.rs
  mistralrs-core/src/pipeline/gguf.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/pipeline/normal.rs
  mistralrs-core/src/pipeline/sampling.rs
  mistralrs-core/src/pipeline/sampling_pipeline.rs
  mistralrs-core/src/prefix_cacher.rs
  mistralrs-core/src/scheduler.rs
  mistralrs-core/src/sequence.rs
  mistralrs-core/src/utils/mod.rs
  mistralrs-core/src/xlora_models/gemma.rs
  mistralrs-core/src/xlora_models/llama.rs
  mistralrs-core/src/xlora_models/mistral.rs
  mistralrs-core/src/xlora_models/mixtral.rs
  mistralrs-core/src/xlora_models/mod.rs
  mistralrs-core/src/xlora_models/phi2.rs
  mistralrs-core/src/xlora_models/phi3.rs
  mistralrs-core/src/xlora_models/quantized_llama.rs
  mistralrs-server/src/main.rs
Labels: backend

#267 Support EOF in interactive mode
  mistralrs-server/src/interactive_mode.rs
Labels: fix

#268 Fix concat in PhiRotaryEmbedding
  mistralrs-core/src/layers.rs
Labels: fix

#270 Warmup pass for mistralrs-bench
  mistralrs-bench/src/main.rs
Labels: new feature

#274 Add build.rs to PyO3 to improve compat when extension_module
  Cargo.toml
  mistralrs-pyo3/Cargo.toml
  mistralrs-pyo3/build.rs
Labels: fix

#276 Add the quantized phi3 model
  mistralrs-core/src/layers.rs
  mistralrs-core/src/models/mod.rs
  mistralrs-core/src/models/quantized_phi3.rs
  mistralrs-core/src/pipeline/gguf.rs
Labels: models

#280 Remove sliding window mask from quantized phi3
  mistralrs-core/src/models/quantized_phi3.rs
Labels: urgent, fix

#279 More intelligent scheduler
  mistralrs-core/src/scheduler.rs
  mistralrs-core/src/sequence.rs
Labels: new feature

#242 Implement Speculative Decoding
  README.md
  examples/llama_index/cookbook.ipynb
  examples/llama_index/mistral_gguf.py
  examples/llama_index/streaming.py
  examples/llama_index/xlora_gguf.py
  examples/python/speculative.py
  examples/python/speculative_xlora.py
  integrations/llama_index_integration.py
  mistralrs-core/src/layers.rs
  mistralrs-core/src/lib.rs
  mistralrs-core/src/models/gemma.rs
  mistralrs-core/src/models/llama.rs
  mistralrs-core/src/models/mistral.rs
  mistralrs-core/src/models/mixtral.rs
  mistralrs-core/src/models/phi2.rs
  mistralrs-core/src/models/phi3.rs
  mistralrs-core/src/models/quantized_llama.rs
  mistralrs-core/src/models/quantized_phi2.rs
  mistralrs-core/src/models/quantized_phi3.rs
  mistralrs-core/src/models/qwen2.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/pipeline/sampling.rs
  mistralrs-core/src/pipeline/speculative.rs
  mistralrs-core/src/sequence.rs
  mistralrs-core/src/toml_selector.rs
  mistralrs-core/src/xlora_models/gemma.rs
  mistralrs-core/src/xlora_models/llama.rs
  mistralrs-core/src/xlora_models/mistral.rs
  mistralrs-core/src/xlora_models/mixtral.rs
  mistralrs-core/src/xlora_models/phi2.rs
  mistralrs-core/src/xlora_models/phi3.rs
  mistralrs-core/src/xlora_models/quantized_llama.rs
  mistralrs-lora/src/layer.rs
  mistralrs-pyo3/mistralrs.pyi
  mistralrs-pyo3/src/lib.rs
  toml-selectors/speculative-gguf.toml
  toml-selectors/speculative-same-gguf.toml
Labels: new feature, backend, models

#293 Add X-LoRA support for GGUF
  docs/ADAPTER_MODELS.md
  mistralrs-core/src/pipeline/ggml.rs
  mistralrs-core/src/pipeline/gguf.rs
  mistralrs-core/src/xlora_models/mod.rs
  mistralrs-core/src/xlora_models/quantized_phi3.rs
Labels: models

#272 Add some "senseful" fallbacks for `isq`
  mistralrs-core/src/pipeline/mod.rs
Labels: new feature, backend

#297 Make speculative decoding faster without anything fancy
  mistralrs-core/src/pipeline/speculative.rs
Labels: optimization

#301 Add terminate on next step handler via ctrlc
  mistralrs-core/Cargo.toml
  mistralrs-core/src/engine/mod.rs
  mistralrs-core/src/lib.rs
  mistralrs-core/src/scheduler.rs
  mistralrs-core/src/sequence.rs
  mistralrs-server/src/main.rs
Labels: new feature

#300 bug fix: llama kv cache part
  mistralrs-core/src/models/llama.rs
Labels: fix

#317 Matmul via f16 when possible
  Cargo.toml
  mistralrs-core/Cargo.toml
  mistralrs-core/src/layers.rs
  mistralrs-core/src/lib.rs
  mistralrs-core/src/lora/loralinear.rs
  mistralrs-core/src/lora/mod.rs
  mistralrs-core/src/lora/qloralinear.rs
  mistralrs-core/src/models/gemma.rs
  mistralrs-core/src/models/llama.rs
  mistralrs-core/src/models/mistral.rs
  mistralrs-core/src/models/mixtral.rs
  mistralrs-core/src/models/phi2.rs
  mistralrs-core/src/models/phi3.rs
  mistralrs-core/src/models/quantized_llama.rs
  mistralrs-core/src/models/quantized_phi2.rs
  mistralrs-core/src/models/quantized_phi3.rs
  mistralrs-core/src/models/qwen2.rs
  mistralrs-core/src/pipeline/ggml.rs
  mistralrs-core/src/pipeline/gguf.rs
  mistralrs-core/src/pipeline/loaders.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/pipeline/normal.rs
  mistralrs-core/src/utils/varbuilder_utils.rs
  mistralrs-core/src/xlora_models/gemma.rs
  mistralrs-core/src/xlora_models/llama.rs
  mistralrs-core/src/xlora_models/mistral.rs
  mistralrs-core/src/xlora_models/mixtral.rs
  mistralrs-core/src/xlora_models/mod.rs
  mistralrs-core/src/xlora_models/phi2.rs
  mistralrs-core/src/xlora_models/phi3.rs
  mistralrs-core/src/xlora_models/quantized_llama.rs
  mistralrs-core/src/xlora_models/quantized_phi3.rs
  mistralrs-lora/Cargo.toml
  mistralrs-lora/README.md
  mistralrs-lora/src/layer.rs
Labels: optimization

#325 Use cuBLASlt in attention
  mistralrs-core/Cargo.toml
  mistralrs-core/src/cublaslt/api.rs
  mistralrs-core/src/cublaslt/mod.rs
  mistralrs-core/src/layers.rs
  mistralrs-core/src/lib.rs
  mistralrs-core/src/models/gemma.rs
  mistralrs-core/src/models/llama.rs
  mistralrs-core/src/models/mistral.rs
  mistralrs-core/src/models/mixtral.rs
  mistralrs-core/src/models/phi2.rs
  mistralrs-core/src/models/phi3.rs
  mistralrs-core/src/models/quantized_llama.rs
  mistralrs-core/src/models/quantized_phi2.rs
  mistralrs-core/src/models/quantized_phi3.rs
  mistralrs-core/src/models/qwen2.rs
  mistralrs-core/src/xlora_models/gemma.rs
  mistralrs-core/src/xlora_models/llama.rs
  mistralrs-core/src/xlora_models/mistral.rs
  mistralrs-core/src/xlora_models/mixtral.rs
  mistralrs-core/src/xlora_models/phi2.rs
  mistralrs-core/src/xlora_models/phi3.rs
  mistralrs-core/src/xlora_models/quantized_llama.rs
  mistralrs-core/src/xlora_models/quantized_phi3.rs
Labels: optimization

#361 fix: Ensure committed files are normalized to LF
  .gitattributes
  .github/workflows/build_cuda_all.yaml
  Dockerfile.cuda-all
Labels: fix

#359 Disable cublaslt if using f16 kernels
  mistralrs-core/src/layers.rs
Labels: optimization

#356 refactor: GGUF + GGML Loaders with `ModelKind`
  mistralrs-core/Cargo.toml
  mistralrs-core/src/models/quantized_llama.rs
  mistralrs-core/src/models/quantized_phi2.rs
  mistralrs-core/src/models/quantized_phi3.rs
  mistralrs-core/src/pipeline/ggml.rs
  mistralrs-core/src/pipeline/gguf.rs
  mistralrs-core/src/pipeline/mod.rs
  mistralrs-core/src/pipeline/normal.rs
  mistralrs-core/src/utils/mod.rs
  mistralrs-core/src/utils/model_config.rs
  mistralrs-core/src/xlora_models/gemma.rs
  mistralrs-core/src/xlora_models/quantized_llama.rs
  mistralrs-core/src/xlora_models/quantized_phi3.rs
Labels: documentation, models, fix
